### ISSUE TITLE
Virtual Memory Exhausted

### ISSUE THREAD

**Issue by privatenode** [amingilani/mining-scripts#1]
I'm trying your scripts on a 765MB memory vultr cloud, with 1 CPU.

the scripts shows some error and can not proceed

Dec 13 01:55:39 SillyconVally2 miner:  Scanning dependencies of target nheqminer_cpu
Dec 13 01:55:39 SillyconVally2 miner:  [  5%] Building CXX object CMakeFiles/nheqminer_cpu.dir/root/nheqminer/nheqminer/amount.cpp.o
Dec 13 01:55:41 SillyconVally2 miner:  [ 11%] Building CXX object CMakeFiles/nheqminer_cpu.dir/root/nheqminer/nheqminer/api.cpp.o
Dec 13 01:55:45 SillyconVally2 miner:  [ 17%] Building CXX object CMakeFiles/nheqminer_cpu.dir/root/nheqminer/nheqminer/arith_uint256.cpp.o
Dec 13 01:55:45 SillyconVally2 miner:  [ 23%] Building CXX object CMakeFiles/nheqminer_cpu.dir/root/nheqminer/nheqminer/crypto/sha256.cpp.o
Dec 13 01:55:46 SillyconVally2 miner:  [ 29%] Building CXX object CMakeFiles/nheqminer_cpu.dir/root/nheqminer/nheqminer/json/json_spirit_reader.cpp.o
Dec 13 01:56:00 SillyconVally2 miner:  virtual memory exhausted: Cannot allocate memory
Dec 13 01:56:01 SillyconVally2 miner:  make[2]: *** [CMakeFiles/nheqminer_cpu.dir/root/nheqminer/nheqminer/json/json_spirit_reader.cpp.o] Error 1
Dec 13 01:56:01 SillyconVally2 miner:  make[1]: *** [CMakeFiles/nheqminer_cpu.dir/all] Error 2
Dec 13 01:56:01 SillyconVally2 miner:  make: *** [all] Error 2
Dec 13 01:56:01 SillyconVally2 miner:  running miner
Dec 13 01:56:01 SillyconVally2 miner:  bash: line 22: /root/nheqminer/Linux_cmake/nheqminer_cpu/nheqminer_cpu: No such file or directory

**Comment by privatenode** [comment]
what's your scripts minimum required memory?

**Comment by amingilani** [comment]
@privatenode, the script attempts to compile https://github.com/nicehash/nheqminer and it seems that 765MB isn't enough memory for it.

I'm reporting this bug in their repo, and it depends on their answer, but in the meantime, consider using a slightly bigger instance?

**Comment by amingilani** [comment]
I've reproduced this issue on a smaller instance and can confirm it's a memory problem.

**Comment by privatenode** [comment]
Hello @amingilani , found issue, its a swap thing. not enough swap caused virtual memory exhausted.

**Comment by privatenode** [comment]
can i add some thing to your script ensure there is enough swap to build this thing?

**Comment by amingilani** [comment]
Please! Pull requests are totally appreciated!

**Comment by privatenode** [comment]
so, what kind of cloud or VM you used for that screenshot sol/S? about 13-15 avg.

**Comment by privatenode** [comment]
what kind of instance did you uses to create that screenshot Sol/S?

**Comment by privatenode** [comment]
I'm totally confused, you must made some changes , i can't even run this script anymore.

Dec 13 05:24:45 core2 initialize:  Digest: sha256:613ca2e90d24f041c6b80c380a33a25720cf45bbe1e74609c0e3184e70e4d808
Dec 13 05:24:45 core2 initialize:  Status: Downloaded newer image for amingilani/nheqminer:latest
Dec 13 05:24:45 core2 initialize:  bash: line 23: cd: HOME not set
Dec 13 05:24:45 core2 initialize:  running worker
Dec 13 05:24:45 core2 initialize:  Cloning into 'scripts'...
Dec 13 05:24:46 core2 miner:  running miner
Dec 13 05:24:46 core2 miner:  sessions should be nested with care, unset $TMUX to force
Dec 13 05:24:46 core2 kernel:  [   75.280101] aufs au_opts_parse:1155:docker[9087]: unknown option dirperm1
Dec 13 05:24:46 core2 miner:  time="2016-12-13T13:24:46Z" level=fatal msg="Error response from daemon: Cannot start container af9efa047741881334b92c4be671f45ffa085cea6dcb0bf0cef225b5159645b9: [8] System error: mountpoint for devices not found"

**Comment by amingilani** [comment]
@privatenode sorry about that! Entirely my bad, i've upgraded the script so that it fetches a prebuilt image from the docker registry.

Please try now.

**Comment by privatenode** [comment]
alright , will do , just expanded my swap and fixed previous issue. although, what kind of instance you get that hashrate?

**Comment by amingilani** [comment]
I was using Digital Ocean to benchmark this in the morning, but then I found out that they didn't allow miners on their droplets. Switched to a more lenient provider now, but the hashrate is very little there :)

**Comment by privatenode** [comment]
yes, for a $5 instance with one CPU, only runs 5.2-5.5 Sols/Second, that ain't gonna make any profit.

**Comment by amingilani** [comment]
Totally. If the miner works for you new, please feel free to close this issue!

**Comment by privatenode** [comment]
well, i checked it out, its not against their TOS, but still not profitable.

**Comment by privatenode** [comment]
issue resolved, thanks amingilani

**Comment by amingilani** [comment]
Anytime! Thank you for trying this out and helping me improve it!
